const API_URL = 'https://api.uphold.com/v0/ticker/';
const DEFAULT_CURRENCY_PAIR = 'BTC-USD';
const DEFAULT_PRICE_OSCILLATION_PERCENTAGE = 0.01;
const DEFAULT_FETCH_INTERVAL = 5000;
const MAXIMUM_PRICE_OSCILLATION_PERCENTAGE = 10;
const MINIMUM_PRICE_OSCILLATION_PERCENTAGE = 0.001;
const MAXIMUM_FETCH_INTERVAL = 60000;
const MINIMUM_FETCH_INTERVAL = 1000;

module.exports = {  API_URL,    
                    DEFAULT_CURRENCY_PAIR,
                    DEFAULT_PRICE_OSCILLATION_PERCENTAGE,
                    DEFAULT_FETCH_INTERVAL,
                    MAXIMUM_PRICE_OSCILLATION_PERCENTAGE,
                    MINIMUM_PRICE_OSCILLATION_PERCENTAGE,
                    MAXIMUM_FETCH_INTERVAL,
                    MINIMUM_FETCH_INTERVAL
                };